### ISSUE TITLE
Brig mizen topmast winch issue. (bug)

### ISSUE THREAD

**Issue by kapi33333** [NANDbrew/ShipyardExpansion#15]
The lateen trim winch is not working in this setup where there are already 2 other winches for simmilar sails there, it spins freely when holding W(release) as if loosening the sail out but the sail remains unmoving. None such issue on other topmasts with the same type of sail.
![Brig mizen topmast winch issue](https://github.com/user-attachments/assets/466a7a71-3f56-4244-9c42-aecbdb120535)

**Comment by NANDbrew** [comment]
2927e21
